name: Build WebGL Pipeline üñ•Ô∏è

on: push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  # pullandpush:
  #   name: Build WebGL
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout code manual
  #       run: |

  # checkLicense:
  #   name: Check for the Unity license ‚òëÔ∏è
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Fail - No license ‚ò†Ô∏è
  #       if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
  #       run: exit 1

  # reproduce:
  #   runs-on: windows-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         ssh-key: ${{ secrets.SSH_PRIVATE }}

  #-------------------------------------------------------------------------------------#

  # checkoutCodeManual:
  #   runs-on: windows-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         ssh-key: ${{ secrets.SSH_PRIVATE }}

  #     - name: Set up Git
  #       run: |
  #         git config --global core.compression 0
  #         git config --global http.version HTTP/1.1
  #         git config --global http.postBuffer 1024M
  #         git config --global user.name quangnguyen11
  #         git config --global user.email dquang888@gmail.com

  #     - name: Display Git version
  #       run: git --version

  #     - name: Display Git status
  #       run: git status

  #     - name: Push code
  #       run: |
  #         echo 'test' > log.txt
  #         git add .
  #         git commit -m "add test"
  #         git push -u origin master

  #-------------------------------------------------------------------------------------#

  buildWebGL:
    name: Build WebGL
    runs-on: windows-latest
    steps:
      - name: Checkout code manual
        run: |
          git --version

          git config --global user.name quangnguyen11
          git config --global user.email dquang888@gmail.com

          git config --global core.compression 0
          git config --global core.packedGitLimit 512m
          git config --global core.packedGitWindowSize 512m

          git config --global pack.window 1
          git config --global pack.windowMemory 4096m
          git config --global pack.packSizeLimit 2048m
          git config --global pack.deltaCacheSize 2048m

          git config --global http.version HTTP/1.1
          git config --global http.postBuffer 1024M
          git config --global http.maxRequestBuffer 512M

          git config --global pack.window 1

          # git config --global url."https://github.com/".insteadOf git@github.com:
          # git config --global url."https://".insteadOf git://

          set GIT_TRACE_PACKET=1
          set GIT_TRACE=1
          set GIT_CURL_VERBOSE=1

          cd\

          pwd
          dir
          mkdir .ssh

          cd .ssh
          echo "${{ secrets.SSH_KEY }}" > id_rsa.pub
          echo "${{ secrets.SSH_PRIVATE }}" > id_rsa
          ssh-keyscan -t rsa github.com >> known_hosts
          ssh-add id_rsa

          echo . > config
          echo "unity-ci" >> config
          echo "    HostName 127.0.0.1" >> config
          echo "    User unityci" >> config
          echo "    IdentityFile ~/.ssh/id_rsa" >> config

          cat id_rsa.pub
          cat config

          pwd
          dir

          cd ..


          pwd
          dir

          git clone https://quangnguyen11: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@github.com/quangnguyen11/game-ci-test.git
          cd game-ci-test

          pwd
          dir

          # git remote set-url origin https://quangnguyen11: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@github.com:quangnguyen11/game-ci-test.git
          # git remote update
          git remote -v
          git fetch
          git checkout master

          echo 'test' > log.txt
          git add .
          git commit -m "add test"
          git push https://quangnguyen11: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@github.com:quangnguyen11/game-ci-test.git --force

  #-------------------------------------------------------------------------------------#

  # - name: Checkout code
  #   uses: actions/checkout@v3
  #   with:
  #     ref: master

  # - name: Create LFS file list
  #   run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

  # - name: Restore LFS cache
  #   uses: actions/cache@v2
  #   id: lfs-cache
  #   with:
  #     path: .git/lfs
  #     key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

  # - name: Git LFS Pull
  #   run: |
  #     git lfs pull
  #     git add .
  #     git reset --hard

  # - name: Restore Library cache
  #   uses: actions/cache@v3
  #   with:
  #     path: Library
  #     key: Library-build-WebGL
  #     restore-keys: |
  #       Library-build-
  #       Library-

  # - name: Build WebGL
  #   uses: game-ci/unity-builder@v4
  #   env:
  #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  #   with:
  #     targetPlatform: WebGL
  #     buildsPath: Client
  #     buildName: Roguelike

  # to show artifact of builf in Github action uncomment these lines
  # - name: Upload artifact to GH
  #   uses: actions/upload-artifact@v3
  #   with:
  #     name: build-WebGL
  #     path: build/WebGL

  # - name: Push Build to branch build/webgl
  #   run: |
  #     ls -R
  #     git config user.name quangnguyen11
  #     git config user.email quang888@gmail.com
  #     git checkout build/webgl
  #     git add Client
  #     git commit -m "build webgl `date`"
  #     git push
